package field

import (
	"fmt"
	"github.com/xpwu/go-db-mongo/mongodb"
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/tagparser"
	"github.com/xpwu/go-db-mongo/mongodb/updater"
	"go.mongodb.org/mongo-driver/v2/bson"
	"os"
	"path"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"text/template"
)

type ReflectType interface {
	Name() string
	PkgPath() string
}

type reflectType struct {
	name string
	pkg  string
}

func (r *reflectType) Name() string {
	return r.name
}

func (r *reflectType) PkgPath() string {
	return r.pkg
}

type TypeInfo struct {
	T        reflect.Type
	Field    ReflectType
	NewField ReflectType
}

func TypeFor[T any]() reflect.Type {
	return reflect.TypeOf((*T)(nil)).Elem()
}

func NewTypeInfo[T any, FieldType mongodb.Field](creator func(name string) FieldType) TypeInfo {
	name := runtime.FuncForPC(reflect.ValueOf(creator).Pointer()).Name()
	f := strings.FieldsFunc(name, func(r rune) bool {
		if r == '.' {
			return true
		}
		return false
	})

	funName := &reflectType{pkg: strings.Join(f[:len(f)-1], "."), name: f[len(f)-1]}

	return TypeInfo{TypeFor[T](), TypeFor[FieldType](), funName}
}

func typeFieldInfo[T any](field, creator string) TypeInfo {
	return TypeInfo{TypeFor[T](),
		&reflectType{name: field, pkg: TypeFor[BaseField]().PkgPath()},
		&reflectType{name: creator, pkg: TypeFor[BaseField]().PkgPath()}}
}

type CollBuilder struct {
	typeMap map[reflect.Type]TypeInfo
	kindMap map[reflect.Kind]func(reflect.Type) (TypeInfo, bool)
	dir     string
	pkg     string
}

func NewBuilder() *CollBuilder {
	b := &CollBuilder{
		typeMap: make(map[reflect.Type]TypeInfo),
		kindMap: make(map[reflect.Kind]func(reflect.Type) (TypeInfo, bool)),
	}

	b.RegisterType(typeFieldInfo[int]("IntField", "NewIntField"))
	b.RegisterType(typeFieldInfo[int8]("Int8Field", "NewInt8Field"))
	b.RegisterType(typeFieldInfo[int16]("Int16Field", "NewInt16Field"))
	b.RegisterType(typeFieldInfo[int32]("Int32Field", "NewInt32Field"))
	b.RegisterType(typeFieldInfo[int64]("Int64Field", "NewInt64Field"))
	b.RegisterType(typeFieldInfo[uint]("UintField", "NewUintField"))
	b.RegisterType(typeFieldInfo[uint8]("Uint8Field", "NewUint8Field"))
	b.RegisterType(typeFieldInfo[uint16]("Uint16Field", "NewUint16Field"))
	b.RegisterType(typeFieldInfo[uint32]("Uint32Field", "NewUint32Field"))
	b.RegisterType(typeFieldInfo[uint64]("Uint64Field", "NewUint64Field"))
	b.RegisterType(typeFieldInfo[float32]("Float32Field", "NewFloat32Field"))
	b.RegisterType(typeFieldInfo[float64]("Float64Field", "NewFloat64Field"))
	b.RegisterType(typeFieldInfo[string]("StringField", "NewStringField"))
	b.RegisterType(typeFieldInfo[bool]("BoolField", "NewBoolField"))
	b.RegisterType(typeFieldInfo[bson.Binary]("BinaryField", "NewBinaryField"))
	b.RegisterType(typeFieldInfo[bson.Decimal128]("Decimal128Field", "NewDecimal128Field"))
	b.RegisterType(typeFieldInfo[bson.ObjectID]("ObjectIDField", "NewObjectIDField"))

	b.RegisterKind(reflect.Struct, b.buildStruct)
	//b.RegisterKind(reflect.Slice, b.buildSlice)
	b.RegisterKind(reflect.Ptr, b.buildPtr)

	return b
}

func (b *CollBuilder) ClearType(rt reflect.Type) *CollBuilder {
	delete(b.typeMap, rt)
	return b
}

func (b *CollBuilder) RegisterType(info TypeInfo) *CollBuilder {
	b.typeMap[info.T] = info
	return b
}

func (b *CollBuilder) RegisterKind(k reflect.Kind, f func(rt reflect.Type) (TypeInfo, bool)) *CollBuilder {
	b.kindMap[k] = f
	return b
}

func (b *CollBuilder) buildPtr(t reflect.Type) (ft TypeInfo, ok bool) {
	return b.build(t.Elem())
}

func (b *CollBuilder) build(rt reflect.Type) (ft TypeInfo, ok bool) {
	ft, ok = b.typeMap[rt]
	if ok {
		return
	}

	f := b.kindMap[rt.Kind()]
	ft, ok = f(rt)
	if ok {
		b.typeMap[rt] = ft
	}

	return
}

func (b *CollBuilder) Build(rt reflect.Type) {
	if rt.Kind() == reflect.Ptr {
		rt = rt.Elem()
	}

	b.pkg = rt.PkgPath()
	if b.pkg == "" {
		// 基本类型 就取当前的pkg, 基本类型都是预生成在此pkg中
		// 对于其他pkg为空的类型 暂不支持
		b.pkg = reflect.TypeOf(b).Elem().PkgPath()
	}

	b.build(rt)
}

func firstToLower(s string) string {
	if len(s) == 0 {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

var structCode2 = template.Must(template.New("structCode2").Funcs(template.FuncMap{
	"firstToLower": firstToLower,
}).Parse(`
// Code generated by collbuilder; DO NOT EDIT.

package {{.Pkg}}

import ({{range .Imports}}
  {{.Alias}} "{{.Import}}"
{{end}})

type {{.Name}}Field interface {
	{{.MongoAlias}}.Field
	{{.FilterAlias}}.ComparableFilter[{{.Name}}]
	{{.UpdaterAlias}}.BaseUpdater[{{.Name}}]

{{range .Fields}}
	{{.MethodName}}() {{.FieldName}}
{{end}}
}

type {{.Name|firstToLower}}Field struct {
	{{.FieldAlias}}.BaseField[{{.Name}}]
}

var {{.Name}}Coll = New{{.Name}}Field("")

func New{{.Name}}Field(name string) {{.Name}}Field {
	return &{{.Name|firstToLower}}Field{BaseField: {{.FieldAlias}}.BaseField[{{.Name}}]{name}}
}

{{range .Fields}}
func (s *{{$.Name|firstToLower}}Field) {{.MethodName}}() {{.FieldName}} {
	return {{.NewField}}({{$.FieldAlias}}.SubField(s.FullName(), "{{.TagName}}"))
}
{{end}}
`))

type aliasNames map[string]bool

func (a aliasNames) get(expect string) string {
	test := expect
	num := 1
	for (a)[test] {
		num++
		test = fmt.Sprintf("%s%d", expect, num)
	}
	(a)[test] = true

	return test
}

type allImports struct {
	data  map[string]string
	alias aliasNames
	exc   map[string]bool
}

func newAllImports() *allImports {
	return &allImports{
		data:  make(map[string]string),
		alias: aliasNames{},
		exc:   make(map[string]bool),
	}
}

func (m *allImports) exclude(paths string) {
	m.exc[paths] = true
}

func (m *allImports) add(paths string) (alias string) {
	if paths == "" || m.exc[paths] {
		return ""
	}

	if a, ok := m.data[paths]; ok {
		return a
	}

	a := m.alias.get(path.Base(paths))
	m.data[paths] = a

	return a
	//return a + "."
}

type importTemp struct {
	Alias  string
	Import string
}

func (m *allImports) all() []importTemp {
	ret := make([]importTemp, len(m.data))

	var keys []string
	for k := range m.data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for j, k := range keys {
		ret[j] = importTemp{
			Alias:  m.data[k],
			Import: k,
		}
	}

	return ret
}

func (b *CollBuilder) buildStruct(t reflect.Type) (ft TypeInfo, ok bool) {
	type Field struct {
		MethodName string
		FieldName  string
		TagName    string
		NewField   string
	}

	type st struct {
		Pkg          string
		Name         string
		FieldAlias   string
		MongoAlias   string
		FilterAlias  string
		UpdaterAlias string
		Imports      []importTemp
		Fields       []Field
	}

	thisImports := newAllImports()
	thisImports.exclude(b.pkg)

	// firstly, put this pkg into alias
	thisImports.alias.get(path.Base(b.pkg))

	s := &st{
		Pkg:          path.Base(b.pkg),
		Name:         t.Name(),
		FilterAlias:  thisImports.add(TypeFor[filter.ComparableFilter]().PkgPath()),
		FieldAlias:   thisImports.add(TypeFor[BaseField]().PkgPath()),
		MongoAlias:   thisImports.add(TypeFor[mongodb.Field]().PkgPath()),
		UpdaterAlias: thisImports.add(TypeFor[updater.BaseUpdater]().PkgPath()),
	}

	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		// unexported
		if f.PkgPath != "" {
			continue
		}
		tag, _ := tagparser.StructTagParser(f)
		if tag.Skip {
			continue
		}
		fd := Field{}
		fd.MethodName = f.Name
		fd.TagName = tag.Name
		ft, ok := b.build(f.Type)
		if !ok {
			panic(fmt.Errorf("not support %v", f.Type))
		}
		fd.FieldName = imports.add(ft.F.PkgPath()) + ft.F.Name()
		fd.New = imports.add(ft.NewF.PkgPath()) + ft.NewF.Name()

		// inline 域能进行普通子域访问，但不能有任何操作，也不能在访问路径中添加新的嵌套字段
		if tag.Inline && f.Type.Kind() == reflect.Struct {
			fd.TagName = ""
			fd.New = imports.add(ft.NewF.PkgPath()) + ft.NewF.Name() + "Inline"
		}
		s.Fields = append(s.Fields, fd)
	}

	s.Imports = thisImports.all()

	file, err := os.Create("z" + s.Name + ".go")
	if err != nil {
		panic(err)
	}

	err = structCode.Execute(file, s)
	if err != nil {
		panic(err)
	}

	ft = Type{}
	ft.F = &rTyp{s.Name, b.pkg}
	ft.NewF = &rTyp{"New" + s.Name, b.pkg}

	return ft, true
}
