package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/updater"

	"go.mongodb.org/mongo-driver/v2/bson/primitive"
)

type Binary0F struct {
	*Binary0FUpdaterF
	*baseKey
	*Binary0FFilterF
}

func (a *Binary0F) FullName() string {
	return a.baseKey.FullName()
}

type Binary0FUpdaterF struct {
	*baseUpdater
}

type Binary0FFilterF struct {
	*baseFilter
}

func NewBinary0F(fName string) *Binary0F {
	uper := &Binary0FUpdaterF{&baseUpdater{&base{fName}}}
	pri := &baseKey{uper.base}
	flt := &Binary0FFilterF{&baseFilter{uper.base}}

	return &Binary0F{uper, pri, flt}
}

func (i *Binary0FFilterF) In(values []primitive.Binary) filter.Filter {
	return filter.New(i, "$in", values)
}

func (i *Binary0FFilterF) Nin(values []primitive.Binary) filter.Filter {
	return filter.New(i, "$nin", values)
}

func (i *Binary0FUpdaterF) Set(value primitive.Binary) updater.Updater {
	return updater.New(i, "$set", value)
}

func (i *Binary0FUpdaterF) SetOnIns(value primitive.Binary) updater.Updater {
	return updater.New(i, "$setOnInsert", value)
}
