package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/updater"
)

type Bool0F struct {
	*Bool0FUpdaterF
	*BaseKey
	*Bool0FFilterF
}

func (a *Bool0F) FullName() string {
	return a.BaseKey.FullName()
}

type Bool0FUpdaterF struct {
	*BaseUpdater
}

type Bool0FFilterF struct {
	*BaseFilter
}

func NewBool0F(fName string) *Bool0F {
	uper := &Bool0FUpdaterF{&BaseUpdater{&baseField{fName}}}
	pri := &BaseKey{uper.Base}
	flt := &Bool0FFilterF{&BaseFilter{uper.Base}}

	return &Bool0F{uper, pri, flt}
}

func (i *Bool0FFilterF) Eq(value bool) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, value)
}

func (i *Bool0FFilterF) Ne(value bool) filter.Filter {
	return filter.CompareByValue(i, filter.NE, value)
}

func (i *Bool0FFilterF) NeField(f *Bool0F) filter.Filter {
	return filter.CompareByField(i, filter.NE, f)
}

func (i *Bool0FFilterF) EqField(f *Bool0F) filter.Filter {
	return filter.CompareByField(i, filter.EQ, f)
}

func (i *Bool0FFilterF) Gte(value bool) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, value)
}

func (i *Bool0FFilterF) Lte(value bool) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, value)
}

func (i *Bool0FFilterF) GteField(f *Bool0F) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, f)
}

func (i *Bool0FFilterF) LteField(f *Bool0F) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, f)
}

func (i *Bool0FFilterF) Gt(value bool) filter.Filter {
	return filter.CompareByValue(i, filter.GT, value)
}

func (i *Bool0FFilterF) Lt(value bool) filter.Filter {
	return filter.CompareByValue(i, filter.LT, value)
}

func (i *Bool0FFilterF) GtField(f *Bool0F) filter.Filter {
	return filter.CompareByValue(i, filter.GT, f)
}

func (i *Bool0FFilterF) LtField(f *Bool0F) filter.Filter {
	return filter.CompareByValue(i, filter.LT, f)
}

func (i *Bool0FFilterF) In(values []bool) filter.Filter {
	return filter.New(i, "$in", values)
}

func (i *Bool0FFilterF) Nin(values []bool) filter.Filter {
	return filter.New(i, "$nin", values)
}

func (i *Bool0FUpdaterF) Min(value bool) updater.Updater {
	return updater.New(i, "$min", value)
}

func (i *Bool0FUpdaterF) Max(value bool) updater.Updater {
	return updater.New(i, "$max", value)
}

func (i *Bool0FUpdaterF) Set(value bool) updater.Updater {
	return updater.New(i, "$set", value)
}

func (i *Bool0FUpdaterF) SetOnIns(value bool) updater.Updater {
	return updater.New(i, "$setOnInsert", value)
}
