package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"go.mongodb.org/mongo-driver/v2/bson/primitive"
	"reflect"
)

func init() {
	builderR0 = func(b *Builder) {

		b.RegisterType(reflect.TypeOf((*int)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Int0F)(nil)).Elem(),
			NewF: NewTypByFunc(NewInt0F),
		})

		b.RegisterType(reflect.TypeOf((*int8)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Int80F)(nil)).Elem(),
			NewF: NewTypByFunc(NewInt80F),
		})

		b.RegisterType(reflect.TypeOf((*int16)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Int160F)(nil)).Elem(),
			NewF: NewTypByFunc(NewInt160F),
		})

		b.RegisterType(reflect.TypeOf((*int32)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Int320F)(nil)).Elem(),
			NewF: NewTypByFunc(NewInt320F),
		})

		b.RegisterType(reflect.TypeOf((*int64)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Int640F)(nil)).Elem(),
			NewF: NewTypByFunc(NewInt640F),
		})

		b.RegisterType(reflect.TypeOf((*uint)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Uint0F)(nil)).Elem(),
			NewF: NewTypByFunc(NewUint0F),
		})

		b.RegisterType(reflect.TypeOf((*uint8)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Uint80F)(nil)).Elem(),
			NewF: NewTypByFunc(NewUint80F),
		})

		b.RegisterType(reflect.TypeOf((*uint16)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Uint160F)(nil)).Elem(),
			NewF: NewTypByFunc(NewUint160F),
		})

		b.RegisterType(reflect.TypeOf((*uint32)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Uint320F)(nil)).Elem(),
			NewF: NewTypByFunc(NewUint320F),
		})

		b.RegisterType(reflect.TypeOf((*uint64)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Uint640F)(nil)).Elem(),
			NewF: NewTypByFunc(NewUint640F),
		})

		b.RegisterType(reflect.TypeOf((*string)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*String0F)(nil)).Elem(),
			NewF: NewTypByFunc(NewString0F),
		})

		b.RegisterType(reflect.TypeOf((*float32)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Float320F)(nil)).Elem(),
			NewF: NewTypByFunc(NewFloat320F),
		})

		b.RegisterType(reflect.TypeOf((*float64)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Float640F)(nil)).Elem(),
			NewF: NewTypByFunc(NewFloat640F),
		})

		b.RegisterType(reflect.TypeOf((*bool)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Bool0F)(nil)).Elem(),
			NewF: NewTypByFunc(NewBool0F),
		})

		b.RegisterType(reflect.TypeOf((*primitive.Binary)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Binary0F)(nil)).Elem(),
			NewF: NewTypByFunc(NewBinary0F),
		})

		b.RegisterType(reflect.TypeOf((*primitive.Decimal128)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*Decimal1280F)(nil)).Elem(),
			NewF: NewTypByFunc(NewDecimal1280F),
		})

		b.RegisterType(reflect.TypeOf((*primitive.ObjectID)(nil)).Elem(), Type{
			F:    reflect.TypeOf((*ObjectID0F)(nil)).Elem(),
			NewF: NewTypByFunc(NewObjectID0F),
		})

	}
}
