package field

// ---- auto generated by builder.go, NOT modify this file ----

import (
	fmt "fmt"
	filter "github.com/xpwu/go-db-mongo/mongodb/filter"
	updater "github.com/xpwu/go-db-mongo/mongodb/updater"
	bson "go.mongodb.org/mongo-driver/v2/bson"
	primitive "go.mongodb.org/mongo-driver/v2/bson/primitive"
)

type Decimal1281Field struct {
	*Array
}

func NewDecimal1281Field(fName string) *Decimal1281Field {
	return &Decimal1281Field{NewArray(fName)}
}

func (i *Decimal1281Field) EleAt(index int) *Decimal1280F {
	return NewDecimal1280F(fmt.Sprintf("%s.%d", i.FullName(), index))
}

// 数组的某一个元素，有时也可以理解为 数组的任何一个元素
func (i *Decimal1281Field) EleOne() *Decimal1280F {
	return NewDecimal1280F(i.FullName())
}

// update 操作中被filter匹配的那第一个元素
func (i *Decimal1281Field) EleThat() *Decimal1280FUpdaterF {
	return NewDecimal1280F(i.FullName() + ".$").Decimal1280FUpdaterF
}

func (i *Decimal1281Field) EleAll() *Decimal1280FUpdaterF {
	return NewDecimal1280F(i.FullName() + ".$[]").Decimal1280FUpdaterF
}

func (i *Decimal1281Field) EleByFid(identifier string) *Decimal1280FUpdaterF {
	return NewDecimal1280F(fmt.Sprintf("%s.$[%s]", i.FullName(), i.FullName()+identifier)).Decimal1280FUpdaterF
}

func (i *Decimal1281Field) DeclFid(identifier string) *Decimal1280FFilterF {
	return NewDecimal1280F(i.FullName() + identifier).Decimal1280FFilterF
}

func (i *Decimal1281Field) Include(a []primitive.Decimal128) filter.Filter {
	return filter.New(i, "$all", a)
}

func (i *Decimal1281Field) Eq(a []primitive.Decimal128) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, a)
}

func (i *Decimal1281Field) Set(a []primitive.Decimal128) updater.Updater {
	return updater.New(i, "$set", a)
}

func (i *Decimal1281Field) AddToSet(value primitive.Decimal128) updater.Updater {
	return updater.New(i, "$addToSet", value)
}

func (i *Decimal1281Field) AddToSetValues(a []primitive.Decimal128) updater.Updater {
	return updater.New(i, "$addToSet", bson.M{"$each": a})
}

func (i *Decimal1281Field) Pull(value primitive.Decimal128) updater.Updater {
	return updater.New(i, "$pull", value)
}

func (i *Decimal1281Field) PullAll(a []primitive.Decimal128) updater.Updater {
	return updater.New(i, "$pullAll", a)
}

func (i *Decimal1281Field) Push(value primitive.Decimal128) updater.Updater {
	return updater.New(i, "$push", value)
}

func (i *Decimal1281Field) PushByModifier(m updater.PushModifier, each []primitive.Decimal128) updater.Updater {
	return updater.PushByModifier(i, m, each)
}
