package field

// ---- auto generated by builder.go, NOT modify this file ----

import (
	fmt "fmt"
	filter "github.com/xpwu/go-db-mongo/mongodb/filter"
	updater "github.com/xpwu/go-db-mongo/mongodb/updater"
	bson "go.mongodb.org/mongo-driver/v2/bson"
)

type Float641Field struct {
	*Array
}

func NewFloat641Field(fName string) *Float641Field {
	return &Float641Field{NewArray(fName)}
}

func (i *Float641Field) EleAt(index int) *Float640F {
	return NewFloat640F(fmt.Sprintf("%s.%d", i.FullName(), index))
}

// 数组的某一个元素，有时也可以理解为 数组的任何一个元素
func (i *Float641Field) EleOne() *Float640F {
	return NewFloat640F(i.FullName())
}

// update 操作中被filter匹配的那第一个元素
func (i *Float641Field) EleThat() *Float640FUpdaterF {
	return NewFloat640F(i.FullName() + ".$").Float640FUpdaterF
}

func (i *Float641Field) EleAll() *Float640FUpdaterF {
	return NewFloat640F(i.FullName() + ".$[]").Float640FUpdaterF
}

func (i *Float641Field) EleByFid(identifier string) *Float640FUpdaterF {
	return NewFloat640F(fmt.Sprintf("%s.$[%s]", i.FullName(), i.FullName()+identifier)).Float640FUpdaterF
}

func (i *Float641Field) DeclFid(identifier string) *Float640FFilterF {
	return NewFloat640F(i.FullName() + identifier).Float640FFilterF
}

func (i *Float641Field) Include(a []float64) filter.Filter {
	return filter.New(i, "$all", a)
}

func (i *Float641Field) Eq(a []float64) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, a)
}

func (i *Float641Field) Set(a []float64) updater.Updater {
	return updater.New(i, "$set", a)
}

func (i *Float641Field) AddToSet(value float64) updater.Updater {
	return updater.New(i, "$addToSet", value)
}

func (i *Float641Field) AddToSetValues(a []float64) updater.Updater {
	return updater.New(i, "$addToSet", bson.M{"$each": a})
}

func (i *Float641Field) Pull(value float64) updater.Updater {
	return updater.New(i, "$pull", value)
}

func (i *Float641Field) PullAll(a []float64) updater.Updater {
	return updater.New(i, "$pullAll", a)
}

func (i *Float641Field) Push(value float64) updater.Updater {
	return updater.New(i, "$push", value)
}

func (i *Float641Field) PushByModifier(m updater.PushModifier, each []float64) updater.Updater {
	return updater.PushByModifier(i, m, each)
}
