package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/updater"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type Int640F struct {
	*Int640FUpdaterF
	*baseKey
	*Int640FFilterF
}

func (a *Int640F) FullName() string {
	return a.baseKey.FullName()
}

type Int640FUpdaterF struct {
	*baseUpdater
}

type Int640FFilterF struct {
	*baseFilter
}

func NewInt640F(fName string) *Int640F {
	uper := &Int640FUpdaterF{&baseUpdater{&base{fName}}}
	pri := &baseKey{uper.base}
	flt := &Int640FFilterF{&baseFilter{uper.base}}

	return &Int640F{uper, pri, flt}
}

func (i *Int640FFilterF) Mod(divisor, remainder int64) filter.Filter {
	return filter.New(i, "$mod", bson.A{divisor, remainder})
}

func (i *Int640FUpdaterF) Inc(num int64) updater.Updater {
	return updater.New(i, "$inc", num)
}

func (i *Int640FUpdaterF) Mul(num int64) updater.Updater {
	return updater.New(i, "$mul", num)
}

func (i *Int640FFilterF) Eq(value int64) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, value)
}

func (i *Int640FFilterF) Ne(value int64) filter.Filter {
	return filter.CompareByValue(i, filter.NE, value)
}

func (i *Int640FFilterF) NeField(f *Int640F) filter.Filter {
	return filter.CompareByField(i, filter.NE, f)
}

func (i *Int640FFilterF) EqField(f *Int640F) filter.Filter {
	return filter.CompareByField(i, filter.EQ, f)
}

func (i *Int640FFilterF) Gte(value int64) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, value)
}

func (i *Int640FFilterF) Lte(value int64) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, value)
}

func (i *Int640FFilterF) GteField(f *Int640F) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, f)
}

func (i *Int640FFilterF) LteField(f *Int640F) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, f)
}

func (i *Int640FFilterF) Gt(value int64) filter.Filter {
	return filter.CompareByValue(i, filter.GT, value)
}

func (i *Int640FFilterF) Lt(value int64) filter.Filter {
	return filter.CompareByValue(i, filter.LT, value)
}

func (i *Int640FFilterF) GtField(f *Int640F) filter.Filter {
	return filter.CompareByValue(i, filter.GT, f)
}

func (i *Int640FFilterF) LtField(f *Int640F) filter.Filter {
	return filter.CompareByValue(i, filter.LT, f)
}

func (i *Int640FFilterF) In(values []int64) filter.Filter {
	return filter.New(i, "$in", values)
}

func (i *Int640FFilterF) Nin(values []int64) filter.Filter {
	return filter.New(i, "$nin", values)
}

func (i *Int640FUpdaterF) Min(value int64) updater.Updater {
	return updater.New(i, "$min", value)
}

func (i *Int640FUpdaterF) Max(value int64) updater.Updater {
	return updater.New(i, "$max", value)
}

func (i *Int640FUpdaterF) Set(value int64) updater.Updater {
	return updater.New(i, "$set", value)
}

func (i *Int640FUpdaterF) SetOnIns(value int64) updater.Updater {
	return updater.New(i, "$setOnInsert", value)
}
