package field

// ---- auto generated by builder.go, NOT modify this file ----

import (
	fmt "fmt"
	filter "github.com/xpwu/go-db-mongo/mongodb/filter"
	updater "github.com/xpwu/go-db-mongo/mongodb/updater"
	bson "go.mongodb.org/mongo-driver/v2/bson"
)

type Int81Field struct {
	*Array
}

func NewInt81Field(fName string) *Int81Field {
	return &Int81Field{NewArray(fName)}
}

func (i *Int81Field) EleAt(index int) *Int80F {
	return NewInt80F(fmt.Sprintf("%s.%d", i.FullName(), index))
}

// 数组的某一个元素，有时也可以理解为 数组的任何一个元素
func (i *Int81Field) EleOne() *Int80F {
	return NewInt80F(i.FullName())
}

// update 操作中被filter匹配的那第一个元素
func (i *Int81Field) EleThat() *Int80FUpdaterF {
	return NewInt80F(i.FullName() + ".$").Int80FUpdaterF
}

func (i *Int81Field) EleAll() *Int80FUpdaterF {
	return NewInt80F(i.FullName() + ".$[]").Int80FUpdaterF
}

func (i *Int81Field) EleByFid(identifier string) *Int80FUpdaterF {
	return NewInt80F(fmt.Sprintf("%s.$[%s]", i.FullName(), i.FullName()+identifier)).Int80FUpdaterF
}

func (i *Int81Field) DeclFid(identifier string) *Int80FFilterF {
	return NewInt80F(i.FullName() + identifier).Int80FFilterF
}

func (i *Int81Field) Include(a []int8) filter.Filter {
	return filter.New(i, "$all", a)
}

func (i *Int81Field) Eq(a []int8) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, a)
}

func (i *Int81Field) Set(a []int8) updater.Updater {
	return updater.New(i, "$set", a)
}

func (i *Int81Field) AddToSet(value int8) updater.Updater {
	return updater.New(i, "$addToSet", value)
}

func (i *Int81Field) AddToSetValues(a []int8) updater.Updater {
	return updater.New(i, "$addToSet", bson.M{"$each": a})
}

func (i *Int81Field) Pull(value int8) updater.Updater {
	return updater.New(i, "$pull", value)
}

func (i *Int81Field) PullAll(a []int8) updater.Updater {
	return updater.New(i, "$pullAll", a)
}

func (i *Int81Field) Push(value int8) updater.Updater {
	return updater.New(i, "$push", value)
}

func (i *Int81Field) PushByModifier(m updater.PushModifier, each []int8) updater.Updater {
	return updater.PushByModifier(i, m, each)
}
