package field

// ---- auto generated by builder.go, NOT modify this file ----

import (
	fmt "fmt"
	filter "github.com/xpwu/go-db-mongo/mongodb/filter"
	updater "github.com/xpwu/go-db-mongo/mongodb/updater"
	bson "go.mongodb.org/mongo-driver/v2/bson"
)

type Int161Field struct {
	*Array
}

func NewInt161Field(fName string) *Int161Field {
	return &Int161Field{NewArray(fName)}
}

func (i *Int161Field) EleAt(index int) *Int160F {
	return NewInt160F(fmt.Sprintf("%s.%d", i.FullName(), index))
}

// 数组的某一个元素，有时也可以理解为 数组的任何一个元素
func (i *Int161Field) EleOne() *Int160F {
	return NewInt160F(i.FullName())
}

// update 操作中被filter匹配的那第一个元素
func (i *Int161Field) EleThat() *Int160FUpdaterF {
	return NewInt160F(i.FullName() + ".$").Int160FUpdaterF
}

func (i *Int161Field) EleAll() *Int160FUpdaterF {
	return NewInt160F(i.FullName() + ".$[]").Int160FUpdaterF
}

func (i *Int161Field) EleByFid(identifier string) *Int160FUpdaterF {
	return NewInt160F(fmt.Sprintf("%s.$[%s]", i.FullName(), i.FullName()+identifier)).Int160FUpdaterF
}

func (i *Int161Field) DeclFid(identifier string) *Int160FFilterF {
	return NewInt160F(i.FullName() + identifier).Int160FFilterF
}

func (i *Int161Field) Include(a []int16) filter.Filter {
	return filter.New(i, "$all", a)
}

func (i *Int161Field) Eq(a []int16) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, a)
}

func (i *Int161Field) Set(a []int16) updater.Updater {
	return updater.New(i, "$set", a)
}

func (i *Int161Field) AddToSet(value int16) updater.Updater {
	return updater.New(i, "$addToSet", value)
}

func (i *Int161Field) AddToSetValues(a []int16) updater.Updater {
	return updater.New(i, "$addToSet", bson.M{"$each": a})
}

func (i *Int161Field) Pull(value int16) updater.Updater {
	return updater.New(i, "$pull", value)
}

func (i *Int161Field) PullAll(a []int16) updater.Updater {
	return updater.New(i, "$pullAll", a)
}

func (i *Int161Field) Push(value int16) updater.Updater {
	return updater.New(i, "$push", value)
}

func (i *Int161Field) PushByModifier(m updater.PushModifier, each []int16) updater.Updater {
	return updater.PushByModifier(i, m, each)
}
