package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/updater"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type Int0F struct {
	*Int0FUpdaterF
	*baseKey
	*Int0FFilterF
}

func (a *Int0F) FullName() string {
	return a.baseKey.FullName()
}

type Int0FUpdaterF struct {
	*baseUpdater
}

type Int0FFilterF struct {
	*baseFilter
}

func NewInt0F(fName string) *Int0F {
	uper := &Int0FUpdaterF{&baseUpdater{&base{fName}}}
	pri := &baseKey{uper.base}
	flt := &Int0FFilterF{&baseFilter{uper.base}}

	return &Int0F{uper, pri, flt}
}

func (i *Int0FFilterF) Mod(divisor, remainder int) filter.Filter {
	return filter.New(i, "$mod", bson.A{divisor, remainder})
}

func (i *Int0FUpdaterF) Inc(num int) updater.Updater {
	return updater.New(i, "$inc", num)
}

func (i *Int0FUpdaterF) Mul(num int) updater.Updater {
	return updater.New(i, "$mul", num)
}

func (i *Int0FFilterF) Eq(value int) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, value)
}

func (i *Int0FFilterF) Ne(value int) filter.Filter {
	return filter.CompareByValue(i, filter.NE, value)
}

func (i *Int0FFilterF) NeField(f *Int0F) filter.Filter {
	return filter.CompareByField(i, filter.NE, f)
}

func (i *Int0FFilterF) EqField(f *Int0F) filter.Filter {
	return filter.CompareByField(i, filter.EQ, f)
}

func (i *Int0FFilterF) Gte(value int) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, value)
}

func (i *Int0FFilterF) Lte(value int) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, value)
}

func (i *Int0FFilterF) GteField(f *Int0F) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, f)
}

func (i *Int0FFilterF) LteField(f *Int0F) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, f)
}

func (i *Int0FFilterF) Gt(value int) filter.Filter {
	return filter.CompareByValue(i, filter.GT, value)
}

func (i *Int0FFilterF) Lt(value int) filter.Filter {
	return filter.CompareByValue(i, filter.LT, value)
}

func (i *Int0FFilterF) GtField(f *Int0F) filter.Filter {
	return filter.CompareByValue(i, filter.GT, f)
}

func (i *Int0FFilterF) LtField(f *Int0F) filter.Filter {
	return filter.CompareByValue(i, filter.LT, f)
}

func (i *Int0FFilterF) In(values []int) filter.Filter {
	return filter.New(i, "$in", values)
}

func (i *Int0FFilterF) Nin(values []int) filter.Filter {
	return filter.New(i, "$nin", values)
}

func (i *Int0FUpdaterF) Min(value int) updater.Updater {
	return updater.New(i, "$min", value)
}

func (i *Int0FUpdaterF) Max(value int) updater.Updater {
	return updater.New(i, "$max", value)
}

func (i *Int0FUpdaterF) Set(value int) updater.Updater {
	return updater.New(i, "$set", value)
}

func (i *Int0FUpdaterF) SetOnIns(value int) updater.Updater {
	return updater.New(i, "$setOnInsert", value)
}
