package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/updater"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type Uint320F struct {
	*Uint320FUpdaterF
	*BaseKey
	*Uint320FFilterF
}

func (a *Uint320F) FullName() string {
	return a.BaseKey.FullName()
}

type Uint320FUpdaterF struct {
	*BaseUpdater
}

type Uint320FFilterF struct {
	*BaseFilter
}

func NewUint320F(fName string) *Uint320F {
	uper := &Uint320FUpdaterF{&BaseUpdater{&base{fName}}}
	pri := &BaseKey{uper.Base}
	flt := &Uint320FFilterF{&BaseFilter{uper.Base}}

	return &Uint320F{uper, pri, flt}
}

func (i *Uint320FFilterF) Mod(divisor, remainder uint32) filter.Filter {
	return filter.New(i, "$mod", bson.A{divisor, remainder})
}

func (i *Uint320FUpdaterF) Inc(num uint32) updater.Updater {
	return updater.New(i, "$inc", num)
}

func (i *Uint320FUpdaterF) Mul(num uint32) updater.Updater {
	return updater.New(i, "$mul", num)
}

func (i *Uint320FFilterF) Eq(value uint32) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, value)
}

func (i *Uint320FFilterF) Ne(value uint32) filter.Filter {
	return filter.CompareByValue(i, filter.NE, value)
}

func (i *Uint320FFilterF) NeField(f *Uint320F) filter.Filter {
	return filter.CompareByField(i, filter.NE, f)
}

func (i *Uint320FFilterF) EqField(f *Uint320F) filter.Filter {
	return filter.CompareByField(i, filter.EQ, f)
}

func (i *Uint320FFilterF) Gte(value uint32) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, value)
}

func (i *Uint320FFilterF) Lte(value uint32) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, value)
}

func (i *Uint320FFilterF) GteField(f *Uint320F) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, f)
}

func (i *Uint320FFilterF) LteField(f *Uint320F) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, f)
}

func (i *Uint320FFilterF) Gt(value uint32) filter.Filter {
	return filter.CompareByValue(i, filter.GT, value)
}

func (i *Uint320FFilterF) Lt(value uint32) filter.Filter {
	return filter.CompareByValue(i, filter.LT, value)
}

func (i *Uint320FFilterF) GtField(f *Uint320F) filter.Filter {
	return filter.CompareByValue(i, filter.GT, f)
}

func (i *Uint320FFilterF) LtField(f *Uint320F) filter.Filter {
	return filter.CompareByValue(i, filter.LT, f)
}

func (i *Uint320FFilterF) In(values []uint32) filter.Filter {
	return filter.New(i, "$in", values)
}

func (i *Uint320FFilterF) Nin(values []uint32) filter.Filter {
	return filter.New(i, "$nin", values)
}

func (i *Uint320FUpdaterF) Min(value uint32) updater.Updater {
	return updater.New(i, "$min", value)
}

func (i *Uint320FUpdaterF) Max(value uint32) updater.Updater {
	return updater.New(i, "$max", value)
}

func (i *Uint320FUpdaterF) Set(value uint32) updater.Updater {
	return updater.New(i, "$set", value)
}

func (i *Uint320FUpdaterF) SetOnIns(value uint32) updater.Updater {
	return updater.New(i, "$setOnInsert", value)
}
