package field

// ---- auto generated by builder.go, NOT modify this file ----

import (
	fmt "fmt"
	filter "github.com/xpwu/go-db-mongo/mongodb/filter"
	updater "github.com/xpwu/go-db-mongo/mongodb/updater"
	bson "go.mongodb.org/mongo-driver/v2/bson"
)

type Uint81Field struct {
	*Array
}

func NewUint81Field(fName string) *Uint81Field {
	return &Uint81Field{NewArray(fName)}
}

func (i *Uint81Field) EleAt(index int) *Uint80F {
	return NewUint80F(fmt.Sprintf("%s.%d", i.FullName(), index))
}

// 数组的某一个元素，有时也可以理解为 数组的任何一个元素
func (i *Uint81Field) EleOne() *Uint80F {
	return NewUint80F(i.FullName())
}

// update 操作中被filter匹配的那第一个元素
func (i *Uint81Field) EleThat() *Uint80FUpdaterF {
	return NewUint80F(i.FullName() + ".$").Uint80FUpdaterF
}

func (i *Uint81Field) EleAll() *Uint80FUpdaterF {
	return NewUint80F(i.FullName() + ".$[]").Uint80FUpdaterF
}

func (i *Uint81Field) EleByFid(identifier string) *Uint80FUpdaterF {
	return NewUint80F(fmt.Sprintf("%s.$[%s]", i.FullName(), i.FullName()+identifier)).Uint80FUpdaterF
}

func (i *Uint81Field) DeclFid(identifier string) *Uint80FFilterF {
	return NewUint80F(i.FullName() + identifier).Uint80FFilterF
}

func (i *Uint81Field) Include(a []uint8) filter.Filter {
	return filter.New(i, "$all", a)
}

func (i *Uint81Field) Eq(a []uint8) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, a)
}

func (i *Uint81Field) Set(a []uint8) updater.Updater {
	return updater.New(i, "$set", a)
}

func (i *Uint81Field) AddToSet(value uint8) updater.Updater {
	return updater.New(i, "$addToSet", value)
}

func (i *Uint81Field) AddToSetValues(a []uint8) updater.Updater {
	return updater.New(i, "$addToSet", bson.M{"$each": a})
}

func (i *Uint81Field) Pull(value uint8) updater.Updater {
	return updater.New(i, "$pull", value)
}

func (i *Uint81Field) PullAll(a []uint8) updater.Updater {
	return updater.New(i, "$pullAll", a)
}

func (i *Uint81Field) Push(value uint8) updater.Updater {
	return updater.New(i, "$push", value)
}

func (i *Uint81Field) PushByModifier(m updater.PushModifier, each []uint8) updater.Updater {
	return updater.PushByModifier(i, m, each)
}
