package field

// ---- auto generated by builder.go, NOT modify this file ----

import (
	fmt "fmt"
	filter "github.com/xpwu/go-db-mongo/mongodb/filter"
	updater "github.com/xpwu/go-db-mongo/mongodb/updater"
	bson "go.mongodb.org/mongo-driver/v2/bson"
)

type Uint321Field struct {
	*Array
}

func NewUint321Field(fName string) *Uint321Field {
	return &Uint321Field{NewArray(fName)}
}

func (i *Uint321Field) EleAt(index int) *Uint320F {
	return NewUint320F(fmt.Sprintf("%s.%d", i.FullName(), index))
}

// 数组的某一个元素，有时也可以理解为 数组的任何一个元素
func (i *Uint321Field) EleOne() *Uint320F {
	return NewUint320F(i.FullName())
}

// update 操作中被filter匹配的那第一个元素
func (i *Uint321Field) EleThat() *Uint320FUpdaterF {
	return NewUint320F(i.FullName() + ".$").Uint320FUpdaterF
}

func (i *Uint321Field) EleAll() *Uint320FUpdaterF {
	return NewUint320F(i.FullName() + ".$[]").Uint320FUpdaterF
}

func (i *Uint321Field) EleByFid(identifier string) *Uint320FUpdaterF {
	return NewUint320F(fmt.Sprintf("%s.$[%s]", i.FullName(), i.FullName()+identifier)).Uint320FUpdaterF
}

func (i *Uint321Field) DeclFid(identifier string) *Uint320FFilterF {
	return NewUint320F(i.FullName() + identifier).Uint320FFilterF
}

func (i *Uint321Field) Include(a []uint32) filter.Filter {
	return filter.New(i, "$all", a)
}

func (i *Uint321Field) Eq(a []uint32) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, a)
}

func (i *Uint321Field) Set(a []uint32) updater.Updater {
	return updater.New(i, "$set", a)
}

func (i *Uint321Field) AddToSet(value uint32) updater.Updater {
	return updater.New(i, "$addToSet", value)
}

func (i *Uint321Field) AddToSetValues(a []uint32) updater.Updater {
	return updater.New(i, "$addToSet", bson.M{"$each": a})
}

func (i *Uint321Field) Pull(value uint32) updater.Updater {
	return updater.New(i, "$pull", value)
}

func (i *Uint321Field) PullAll(a []uint32) updater.Updater {
	return updater.New(i, "$pullAll", a)
}

func (i *Uint321Field) Push(value uint32) updater.Updater {
	return updater.New(i, "$push", value)
}

func (i *Uint321Field) PushByModifier(m updater.PushModifier, each []uint32) updater.Updater {
	return updater.PushByModifier(i, m, each)
}
