package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/updater"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type Uint80F struct {
	*Uint80FUpdaterF
	*baseKey
	*Uint80FFilterF
}

func (a *Uint80F) FullName() string {
	return a.baseKey.FullName()
}

type Uint80FUpdaterF struct {
	*baseUpdater
}

type Uint80FFilterF struct {
	*baseFilter
}

func NewUint80F(fName string) *Uint80F {
	uper := &Uint80FUpdaterF{&baseUpdater{&base{fName}}}
	pri := &baseKey{uper.base}
	flt := &Uint80FFilterF{&baseFilter{uper.base}}

	return &Uint80F{uper, pri, flt}
}

func (i *Uint80FFilterF) Mod(divisor, remainder uint8) filter.Filter {
	return filter.New(i, "$mod", bson.A{divisor, remainder})
}

func (i *Uint80FUpdaterF) Inc(num uint8) updater.Updater {
	return updater.New(i, "$inc", num)
}

func (i *Uint80FUpdaterF) Mul(num uint8) updater.Updater {
	return updater.New(i, "$mul", num)
}

func (i *Uint80FFilterF) Eq(value uint8) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, value)
}

func (i *Uint80FFilterF) Ne(value uint8) filter.Filter {
	return filter.CompareByValue(i, filter.NE, value)
}

func (i *Uint80FFilterF) NeField(f *Uint80F) filter.Filter {
	return filter.CompareByField(i, filter.NE, f)
}

func (i *Uint80FFilterF) EqField(f *Uint80F) filter.Filter {
	return filter.CompareByField(i, filter.EQ, f)
}

func (i *Uint80FFilterF) Gte(value uint8) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, value)
}

func (i *Uint80FFilterF) Lte(value uint8) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, value)
}

func (i *Uint80FFilterF) GteField(f *Uint80F) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, f)
}

func (i *Uint80FFilterF) LteField(f *Uint80F) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, f)
}

func (i *Uint80FFilterF) Gt(value uint8) filter.Filter {
	return filter.CompareByValue(i, filter.GT, value)
}

func (i *Uint80FFilterF) Lt(value uint8) filter.Filter {
	return filter.CompareByValue(i, filter.LT, value)
}

func (i *Uint80FFilterF) GtField(f *Uint80F) filter.Filter {
	return filter.CompareByValue(i, filter.GT, f)
}

func (i *Uint80FFilterF) LtField(f *Uint80F) filter.Filter {
	return filter.CompareByValue(i, filter.LT, f)
}

func (i *Uint80FFilterF) In(values []uint8) filter.Filter {
	return filter.New(i, "$in", values)
}

func (i *Uint80FFilterF) Nin(values []uint8) filter.Filter {
	return filter.New(i, "$nin", values)
}

func (i *Uint80FUpdaterF) Min(value uint8) updater.Updater {
	return updater.New(i, "$min", value)
}

func (i *Uint80FUpdaterF) Max(value uint8) updater.Updater {
	return updater.New(i, "$max", value)
}

func (i *Uint80FUpdaterF) Set(value uint8) updater.Updater {
	return updater.New(i, "$set", value)
}

func (i *Uint80FUpdaterF) SetOnIns(value uint8) updater.Updater {
	return updater.New(i, "$setOnInsert", value)
}
