package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/updater"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type Uint160F struct {
	*Uint160FUpdaterF
	*baseKey
	*Uint160FFilterF
}

func (a *Uint160F) FullName() string {
	return a.baseKey.FullName()
}

type Uint160FUpdaterF struct {
	*baseUpdater
}

type Uint160FFilterF struct {
	*baseFilter
}

func NewUint160F(fName string) *Uint160F {
	uper := &Uint160FUpdaterF{&baseUpdater{&base{fName}}}
	pri := &baseKey{uper.base}
	flt := &Uint160FFilterF{&baseFilter{uper.base}}

	return &Uint160F{uper, pri, flt}
}

func (i *Uint160FFilterF) Mod(divisor, remainder uint16) filter.Filter {
	return filter.New(i, "$mod", bson.A{divisor, remainder})
}

func (i *Uint160FUpdaterF) Inc(num uint16) updater.Updater {
	return updater.New(i, "$inc", num)
}

func (i *Uint160FUpdaterF) Mul(num uint16) updater.Updater {
	return updater.New(i, "$mul", num)
}

func (i *Uint160FFilterF) Eq(value uint16) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, value)
}

func (i *Uint160FFilterF) Ne(value uint16) filter.Filter {
	return filter.CompareByValue(i, filter.NE, value)
}

func (i *Uint160FFilterF) NeField(f *Uint160F) filter.Filter {
	return filter.CompareByField(i, filter.NE, f)
}

func (i *Uint160FFilterF) EqField(f *Uint160F) filter.Filter {
	return filter.CompareByField(i, filter.EQ, f)
}

func (i *Uint160FFilterF) Gte(value uint16) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, value)
}

func (i *Uint160FFilterF) Lte(value uint16) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, value)
}

func (i *Uint160FFilterF) GteField(f *Uint160F) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, f)
}

func (i *Uint160FFilterF) LteField(f *Uint160F) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, f)
}

func (i *Uint160FFilterF) Gt(value uint16) filter.Filter {
	return filter.CompareByValue(i, filter.GT, value)
}

func (i *Uint160FFilterF) Lt(value uint16) filter.Filter {
	return filter.CompareByValue(i, filter.LT, value)
}

func (i *Uint160FFilterF) GtField(f *Uint160F) filter.Filter {
	return filter.CompareByValue(i, filter.GT, f)
}

func (i *Uint160FFilterF) LtField(f *Uint160F) filter.Filter {
	return filter.CompareByValue(i, filter.LT, f)
}

func (i *Uint160FFilterF) In(values []uint16) filter.Filter {
	return filter.New(i, "$in", values)
}

func (i *Uint160FFilterF) Nin(values []uint16) filter.Filter {
	return filter.New(i, "$nin", values)
}

func (i *Uint160FUpdaterF) Min(value uint16) updater.Updater {
	return updater.New(i, "$min", value)
}

func (i *Uint160FUpdaterF) Max(value uint16) updater.Updater {
	return updater.New(i, "$max", value)
}

func (i *Uint160FUpdaterF) Set(value uint16) updater.Updater {
	return updater.New(i, "$set", value)
}

func (i *Uint160FUpdaterF) SetOnIns(value uint16) updater.Updater {
	return updater.New(i, "$setOnInsert", value)
}
