package field

// ---- auto generated by baseTypeBuilder_test.go, NOT modify this file ----

import (
	"github.com/xpwu/go-db-mongo/mongodb/filter"
	"github.com/xpwu/go-db-mongo/mongodb/updater"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type Uint640F struct {
	*Uint640FUpdaterF
	*BaseKey
	*Uint640FFilterF
}

func (a *Uint640F) FullName() string {
	return a.BaseKey.FullName()
}

type Uint640FUpdaterF struct {
	*BaseUpdater
}

type Uint640FFilterF struct {
	*BaseFilter
}

func NewUint640F(fName string) *Uint640F {
	uper := &Uint640FUpdaterF{&BaseUpdater{&base{fName}}}
	pri := &BaseKey{uper.Base}
	flt := &Uint640FFilterF{&BaseFilter{uper.Base}}

	return &Uint640F{uper, pri, flt}
}

func (i *Uint640FFilterF) Mod(divisor, remainder uint64) filter.Filter {
	return filter.New(i, "$mod", bson.A{divisor, remainder})
}

func (i *Uint640FUpdaterF) Inc(num uint64) updater.Updater {
	return updater.New(i, "$inc", num)
}

func (i *Uint640FUpdaterF) Mul(num uint64) updater.Updater {
	return updater.New(i, "$mul", num)
}

func (i *Uint640FFilterF) Eq(value uint64) filter.Filter {
	return filter.CompareByValue(i, filter.EQ, value)
}

func (i *Uint640FFilterF) Ne(value uint64) filter.Filter {
	return filter.CompareByValue(i, filter.NE, value)
}

func (i *Uint640FFilterF) NeField(f *Uint640F) filter.Filter {
	return filter.CompareByField(i, filter.NE, f)
}

func (i *Uint640FFilterF) EqField(f *Uint640F) filter.Filter {
	return filter.CompareByField(i, filter.EQ, f)
}

func (i *Uint640FFilterF) Gte(value uint64) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, value)
}

func (i *Uint640FFilterF) Lte(value uint64) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, value)
}

func (i *Uint640FFilterF) GteField(f *Uint640F) filter.Filter {
	return filter.CompareByValue(i, filter.GTE, f)
}

func (i *Uint640FFilterF) LteField(f *Uint640F) filter.Filter {
	return filter.CompareByValue(i, filter.LTE, f)
}

func (i *Uint640FFilterF) Gt(value uint64) filter.Filter {
	return filter.CompareByValue(i, filter.GT, value)
}

func (i *Uint640FFilterF) Lt(value uint64) filter.Filter {
	return filter.CompareByValue(i, filter.LT, value)
}

func (i *Uint640FFilterF) GtField(f *Uint640F) filter.Filter {
	return filter.CompareByValue(i, filter.GT, f)
}

func (i *Uint640FFilterF) LtField(f *Uint640F) filter.Filter {
	return filter.CompareByValue(i, filter.LT, f)
}

func (i *Uint640FFilterF) In(values []uint64) filter.Filter {
	return filter.New(i, "$in", values)
}

func (i *Uint640FFilterF) Nin(values []uint64) filter.Filter {
	return filter.New(i, "$nin", values)
}

func (i *Uint640FUpdaterF) Min(value uint64) updater.Updater {
	return updater.New(i, "$min", value)
}

func (i *Uint640FUpdaterF) Max(value uint64) updater.Updater {
	return updater.New(i, "$max", value)
}

func (i *Uint640FUpdaterF) Set(value uint64) updater.Updater {
	return updater.New(i, "$set", value)
}

func (i *Uint640FUpdaterF) SetOnIns(value uint64) updater.Updater {
	return updater.New(i, "$setOnInsert", value)
}
